### ISSUE TITLE
Stage 7, Task 3 – Merge Detailed-View into master

### ISSUE THREAD

**Issue by tanyta78** [tanyta78/TeamWorkLive#22]
We’re going to create a pull request for branch Detailed-View. 
You can still create the pull request, but resolving conflicts from the GitHub page is not very elegant. What you need to do now is pull the master into your branch locally, using your favorite method (bash, GUI, IDE plugin).
To pull from the master trough the console, first make sure you’re in the correct local branch by typing git status or git branch. You should be in branch Detailed-View.
Pull from the remote master into the current branch by typing:
git fetch origin
git merge origin/master
First of all, it might be easier to compare the two branches before the merge attempt and manually transfer the changes. If you chose to go that route, back out of the merge by typing (note the double dash):
git reset --hard
The easiest thing to do is probably to keep your branch open and clone the master in another folder, open both files and copy/paste the changes manually.
index.html
prodavachnik.js
api.js
Once everything is cleaned up, we can create a pull request, as instructed above. There should be no more conflicts and the green message “Able to merge” will appear

**Comment by komitoff** [comment]
Close Last issue
